site_name: 'Spring Boot Microservice'
site_description: 'Create a new Spring Boot microservice with Hexagonal Architecture'

nav:
  - Descripción General: index.md
  - Arquitectura: architecture.md
  - Características: features.md
  - Guía de Uso: usage.md

plugins:
  - techdocs-core

theme:
  name: material
  palette:
    primary: teal
    accent: teal
