site_name: WebFlux Reactive Microservice Template
site_description: Technical documentation for reactive WebFlux microservice template with Hexagonal Architecture

docs_dir: docs

nav:
  - Overview: index.md
  - Reactive Architecture: reactive-architecture.md

theme:
  name: material
  palette:
    primary: blue
    accent: light blue

plugins:
  - techdocs-core