site_name: 'Hexagonal Architecture Templates'
site_description: 'Backstage templates for Java microservices with Hexagonal Architecture'

docs_dir: docs

nav:
  - Home: index.md

plugins:
  - techdocs-core