site_name: Spring Boot Microservice Template
site_description: Technical documentation for Spring Boot microservice template with Hexagonal Architecture

docs_dir: docs

nav:
  - Overview: index.md
  - Architecture: architecture.md

theme:
  name: material
  palette:
    primary: green
    accent: light green

plugins:
  - techdocs-core