apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: hexagonal-app-component
  title: Application Layer Template
  description: Capa de aplicación que contiene la lógica de negocio central (Ports e Interactors).
  tags:
    - hexagonal-architecture
    - application-layer
    - java
spec:
  owner: platform-team
  type: other