apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: webflux-service-application-service
  title: Application Services
  description: Implementation of business use cases
  tags:
    - hexagonal-architecture
    - application-layer
    - reactive
    - webflux
spec:
  type: library
  lifecycle: production
  owner: platform-team
  subcomponentOf: component:default/webflux-service-application-layer
