apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: hex-arch-application-layer
  description: Capa de aplicaci√≥n (puertos y casos de uso) de la arquitectura hexagonal.
  tags:
    - hexagonal-architecture
    - application-layer
spec:
  type: service-part 
  owner: platform-team
  lifecycle: production
  partOf:
    - hexagonal-architecture-templates