name: Java CI/CD Pipeline

on:
  push:
    branches: [ "develop", "test", "staging", "main", "hotfix/*" ]
    tags: [ "v*" ]
  pull_request:
    branches: [ "develop", "test", "staging", "main",  ]

jobs:
  # ----------------------------------------------------
  # JOB 1: Build, Test & Package
  # ----------------------------------------------------
  build-and-test:
    name: build-and-test
    runs-on: ubuntu-latest
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: 3. Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-latest-maven-pom-hash
          restore-keys: |
            ubuntu-latest-maven-

      - name: 4. Run unit tests
        run: mvn -B test --file pom.xml
        env:
          MAVEN_OPTS: '-Xmx1024m'

      - name: 5. Generate coverage report
        run: mvn -B jacoco:report --file pom.xml
        env:
          MAVEN_OPTS: '-Xmx1024m'

      - name: 6. Check code coverage
        run: mvn -B verify -DskipTests -Djacoco.skip=false --file pom.xml
        env:
          MAVEN_OPTS: '-Xmx1024m'

      - name: 7. Build and package
        run: mvn -B package -DskipTests --file pom.xml
        env:
          MAVEN_OPTS: '-Xmx1024m'

      - name: 8. Upload JAR artifact
        uses: actions/upload-artifact@v4
        with:
          name: 'movie-service-jar'
          path: target/*.jar
          retention-days: 30

  # ----------------------------------------------------
  # JOB 2: Publish to GitHub Packages
  # ----------------------------------------------------
  publish:
    name: Publish to GitHub Packages
    runs-on: ubuntu-latest
    needs: build-and-test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
    
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: 1. Checkout repository
        uses: actions/checkout@v4

      - name: 2. Set up Java (JDK 21)
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          server-id: github
          server-username: GITHUB_ACTOR
          server-password: GITHUB_TOKEN

      - name: 3. Cache Maven dependencies
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ubuntu-latest-maven-pom-hash
          restore-keys: |
            ubuntu-latest-maven-

      - name: 4. Build and publish to GitHub Packages
        run: mvn -B deploy -DskipTests --file pom.xml
        env:
          MAVEN_OPTS: '-Xmx1024m'