apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: springboot-service-application-mapper
  title: Mappers
  description: MapStruct interfaces for entity transformations
  tags:
    - hexagonal-architecture
    - application-layer
spec:
  type: library
  lifecycle: production
  owner: platform-team
  subcomponentOf: component:default/springboot-service-application-layer
