site_name: 'back-ms-movies-webflux'
site_description: 'Reactive microservice for movie rental management with Spring WebFlux'

docs_dir: docs
nav:
  - Introduction: index.md

plugins:
  - techdocs-core
